### PR TITLE
Added option to spawn additional preview views for FastttFilterCamera.

### PR DESCRIPTION
**Pull request by skeeet**
In my case, using that to implement card-swipe-style selection, while keeping video running.

### CODE REVIEW

**Comment by lauraskelton** [comment]
Thanks for contributing! I haven't had a chance to look it over yet as I'm a bit swamped, but it sounds like a very cool addition!

**Comment by skeeet** [comment]
You're welcome! 
I've closed it for now, since still working on some edge cases, but so far seems fine.
Maybe needs more documentation though:)
Kudos! and thanks for awesome library.

**Comment by skeeet** [comment]
Well, seems like it is working fine, so i guess it is safe to merge it.

**Comment by skeeet** [comment]
Reopened, seems to work fine after a week of testing.

**Comment by skeeet** [comment]
Also changed imports to play nice with framework-based setup.

**Pull request closed without merging**
