### PR TITLE
Added ability to access the original photo when taking a picture with a live filter active

### PR DESCRIPTION
**Pull request by MrMatthewDavis**

### CODE REVIEW

**Comment by MrMatthewDavis** [comment]
Not exactly sure what tests are failing. I didn't make very many changes, so I don't see what would cause any of the tests to fail... @lauraskelton if you could point me in the right direction that would be much appreciated.

**Comment by lauraskelton** [comment]
I'm a bit worried about the memory implications of having three copies of the full-resolution image passed around in the `capturedImage`. There are already some issues with out-of-memory problems on the iPhone 6+ with passing around multiple images. Also, the callback where you are setting the filter properties is overriding the image rotation handling in that method.

**Comment by MrMatthewDavis** [comment]
Yeah you're right. I tried testing on a 6+ and there's no chance it can handle this. I think a better approach would be to simply take the picture without a filter and then apply the filter in my own code after the callback. The problem is, I've reverted back to the original code, and my 6+ crashes almost every time I try to take a picture and I've optimized the rest of my code as best as I could. Any ideas on how to improve this?

**Comment by lauraskelton** [comment]
I'll try to find some time to look into this- doing fancy things with the 6+ camera is tricky due to how much that device's camera image size pushes the limits of its memory.

That sounds like a good solution in the meantime.

**Pull request closed without merging**
